init 2
samatov-rsk/Task34 pull request #1
Opened 2023-09-22 12:33 UTC by samatov-rsk

2023-09-24 14:18 UTC, sokramento requested changes

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/MvcConfig.java
> +public class MvcConfig implements WebMvcConfigurer {
налепил

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/SuccessUserHandler.java
> +    public void onAuthenticationSuccess(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, Authentication authentication) throws IOException {
параметры тут тоже разделить

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoService.java
> +@Service
если тут аннотацию ставишь, то в наследниках необязательно )

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoServiceImpl.java
> +@Transactional
?

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoServiceImpl.java
> +    public void removeUser(long id) {
Long userId

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +@Transactional
и тут, и снизу стоит @Transactional

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +@CrossOrigin(origins = "http://localhost:8089/admin", methods = {RequestMethod.GET, RequestMethod.PUT, RequestMethod.DELETE})
для чего  эта аннотация?

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +        String email = principal.getName();
бесполезная переменная

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        List<User> users = userDao.getAllUsers();
бесполезная переменная

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        }
лучше эту обработку юзера в userDaoImpl делать и кидать исключение если юзер не найдет в бд, в контроллере такое делать не стоит

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +    public ResponseEntity<User> updateUsers(@PathVariable Long id, @RequestBody User updatedUser) {
не updatedUser, а userToUpdate

updatedUser - это юзер после обновления

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(updatedUser);
зачем ты возвращаешь то что прислал ?

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        }
в userDaoImpl это убрать надо

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestUserController.java
> +        String email = principal.getName();
бесполезная переменная

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/UserController.java
> +        String email = principal.getName();
тоже самое

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +@Transactional
тут компонент не нужен и транзакшинал убрать отсюда

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/models/Role.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
статик импорт

2023-09-24 14:18 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/models/User.java
> +@Component
зачем тут компонент аннотация?)))

2023-09-24 17:45 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/MvcConfig.java
> +public class MvcConfig implements WebMvcConfigurer {
fixed

2023-09-24 17:45 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/SuccessUserHandler.java
> +    public void onAuthenticationSuccess(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, Authentication authentication) throws IOException {
fixed

2023-09-24 17:46 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoService.java
> +@Service
fixed

2023-09-24 17:47 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoServiceImpl.java
> +@Transactional
fixed

2023-09-26 14:14 UTC, sokramento commented on docker-compose.yaml
> +  my-db:
также про пустые строки в конце, приучай себя их ставить всегда

2023-09-26 14:15 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoService.java
> +public interface DaoService {
UserService

2023-09-26 14:15 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoServiceImpl.java
> +public class DaoServiceImpl implements DaoService {
naming

2023-09-26 14:16 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    private final UserRepository userRepository;
naming

2023-09-26 14:16 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    public User findByEmail(String email) {
?

2023-09-26 14:16 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    @Transactional
?

2023-09-26 14:24 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +    @GetMapping()
скобки

2023-09-26 14:24 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +    UserService userService;
налепил плюс модификатор где?

2023-09-26 14:27 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +                .stream().map(Role::getName).collect(Collectors.toList()));
разделяй методы в стримах

2023-09-26 14:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +        existingUser.setRoles(existingRoles);
вынеси этот маппинг в отдельный приватный метод

2023-09-26 14:30 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/repositiories/RoleRepository.java
> +}
отступы

2023-09-30 09:07 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +@CrossOrigin(origins = "http://localhost:8089/admin", methods = {RequestMethod.GET, RequestMethod.PUT, RequestMethod.DELETE})
?

2023-09-30 09:14 UTC, sokramento requested changes

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +        return userRepository.findById(userId).orElseThrow(() -> new NotFoundException("User not found by %s" + userId));
может UserNotFoundException ?

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +                .stream().map(Role::getName).collect(Collectors.toList()));
стримы в одну строчку не пишут

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +    public void addUser(User user) {
лучше возвращать юзера которого создал, чтоб видеть результат в постмане например, а если фронту не нужен он - ничего страшного

это можно не исправлять, просто так написал

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +        User existingUser = getUserById(userId);
в параметрах просто user, а в методе userToUpdate

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +    @GetMapping()
не виж изменений

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        }
не вижу изменений

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestUserController.java
> +        User user = userRepository.findByEmail(principal.getName());
бесполезная переменная

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/models/Role.java
> +
порядок важен

2023-09-30 09:14 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/models/User.java
> +    public void setId(Integer id) {
порядок важен

2023-09-30 14:42 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +@CrossOrigin(origins = "http://localhost:8089/admin", methods = {RequestMethod.GET, RequestMethod.PUT, RequestMethod.DELETE})
для обращение к рест апи с других доменов. Я ее поставил чтобы дать разрешение для запросов. В Консоли браузера при выводе всех пользователей выходила ошибка и я почитал что требуется разрешения для обращения. Вот она и стоит

2023-09-30 14:42 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +        String email = principal.getName();
fixed

2023-09-30 14:43 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        List<User> users = userDao.getAllUsers();
fixed

2023-09-30 14:43 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        }
fixed

2023-09-30 14:53 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestUserController.java
> +        String email = principal.getName();
fixed

2023-09-30 14:53 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        }
fixed

2023-09-30 14:53 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +    public ResponseEntity<User> updateUsers(@PathVariable Long id, @RequestBody User updatedUser) {
fixed

2023-09-30 14:53 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(updatedUser);
?

2023-09-30 14:54 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/UserController.java
> +        String email = principal.getName();
fixed

2023-09-30 14:54 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +@Transactional
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/models/Role.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/models/User.java
> +@Component
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on docker-compose.yaml
> +  my-db:
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoService.java
> +public interface DaoService {
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/DaoServiceImpl.java
> +public class DaoServiceImpl implements DaoService {
fixed

2023-09-30 14:55 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    private final UserRepository userRepository;
fixed

2023-09-30 14:56 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    public User findByEmail(String email) {
fixed

2023-09-30 14:57 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserService.java
> +    @Transactional
?? он должен быть транзакшионал
метод работает с базой

2023-09-30 14:58 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +    @GetMapping()
fixed

2023-09-30 14:58 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/AdminController.java
> +    UserService userService;
fixed

2023-09-30 14:58 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +                .stream().map(Role::getName).collect(Collectors.toList()));
fixed

2023-09-30 14:59 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/repositiories/RoleRepository.java
> +}
fixed

2023-09-30 15:00 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +        existingUser.setRoles(existingRoles);
??

2023-09-30 15:01 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +        return userRepository.findById(userId).orElseThrow(() -> new NotFoundException("User not found by %s" + userId));
зачем создавать эксепшон если уже есть готовый. Not found думаю понятно что такого юзера нет, в сообщении.

2023-09-30 15:01 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +                .stream().map(Role::getName).collect(Collectors.toList()));
fixed

2023-09-30 15:02 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +    public void addUser(User user) {
понял

2023-09-30 15:06 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +        User existingUser = getUserById(userId);
fixed

2023-09-30 15:08 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestUserController.java
> +        User user = userRepository.findByEmail(principal.getName());
вот здесь почему бесполезная? а что мне вернуть?

2023-09-30 15:09 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/models/Role.java
> +
fixed

2023-09-30 15:09 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/models/User.java
> +    public void setId(Integer id) {
fixed

2023-09-30 16:30 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/SecurityUserService.java
> +                collect(Collectors.toList());
каждый метод с точкой переносится в стриме

2023-09-30 17:18 UTC, sokramento requested changes

2023-10-01 17:33 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +    public void addUser(User user) {
fixed

2023-10-01 17:34 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(user);
fixed

2023-10-01 17:35 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +                collect(Collectors.toList()));
fixed

2023-10-01 17:35 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/UserServiceImpl.java
> +        userRepository.save(existingUser);
fixed

2023-10-01 17:35 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(user);
fixed

2023-10-01 17:36 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +@CrossOrigin(origins = "http://localhost:8089/admin", methods = {RequestMethod.GET, RequestMethod.PUT, RequestMethod.DELETE})
yes, I know

2023-10-01 17:58 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/SecurityUserService.java
> +    public User getCurrentUser() {
fixed

2023-10-01 17:58 UTC, samatov-rsk commented on src/main/java/ru/kata/spring/boot_security/demo/configs/service/SecurityUserService.java
> +    }
fixed

2023-10-02 11:15 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/dao/UserDaoImpl.java
> +        existingUser.setRoles(existingRoles);
если что-то непонятно, лучше в лс писать по каждому комменту отдельно, потому что время твое уходит всегда и тут, и на работе тоже будет твое время уходить

2023-10-02 11:29 UTC, sokramento requested changes

2023-10-02 11:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(updatedUser);
тут переменные не нужны тебе во всех трех методах, если больше ничего с ними не делаешь

2023-10-02 11:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/controllers/RestAdminController.java
> +        return ResponseEntity.ok(currentUser);
и тут

2023-10-02 11:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/service/SecurityUserService.java
> +    public User getUser(String email) {
@Transactional(readOnly=true)
 getUserByEmail

2023-10-02 11:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/service/SecurityUserService.java
> +    @Transactional
readOnly

2023-10-02 11:29 UTC, sokramento commented on src/main/java/ru/kata/spring/boot_security/demo/service/SecurityUserService.java
> +    @Transactional
readOnly

2023-10-02 11:30 UTC, sokramento approved these changes

2023-10-26 18:13 UTC, merged